### ISSUE TITLE
Conversion Error: MAT File to NWB file format

### ISSUE THREAD

**Issue by imeMFK01** [NeurodataWithoutBorders/mat2nwb#1]
Hi,

I want to convert MAT (MATLAB) file to to the NWB file format:

**1st Attempt: Want to convert only 1 MAT file to the NWB and receiving the below error**
Executed Command: python mat2nwb.py 'C:\Users\XYZ\mat2nwb-master\inputDir\' -M

Error:
len(file_list[0])=0
len(file_list[1])=0
Incorrectly specified input data: num_files == 0

**2nd Attempt: Want to convert 2 MAT file to the NWB and receiving the below error**
Executed Command: python mat2nwb.py 'C:\Users\XYZ\mat2nwb-master\inputDir\' -M

Error:
Incorrectly specified input data: num_files == 0

Can anyone please help me into this?

If you require any additional information then please let me know.

Thanks.

**Comment by oruebel** [comment]
Please use MatNWB https://github.com/NeurodataWithoutBorders/matnwb or PyNWB https://github.com/NeurodataWithoutBorders/pynwb/ for converting data to NWB. `mat2nwb` is an old repo for conversion to NWB 1.0 and does not support conversion to the NWB 2.x. If you have questions, please feel free to reach out the NWB team via the https://github.com/NeurodataWithoutBorders/helpdesk/discussions or by creating issues on the respective repos.
